// Room-level recording SESSION state — the "is anyone in the meeting currently
// recording, and who owns the session?" signal.
//
// Source of truth (06-24 per-speaker pivot, #23/#24): the room Durable Object's
// `recording-state` broadcast — a SINGLE owner holds a server-enforced lock for
// the whole session. Collab.tsx subscribes to that frame and mirrors it here;
// every other surface (the RecordingIndicator header pill, the frame glow, the
// per-participant ParticipantMicRecorder, the host's CloudRecordingControls)
// reads THIS atom. The old host-driven RECORDING_STATE broadcast no longer
// feeds it.
//
// Distinct from `recordingStateAtom` (in audio/audioState.ts), which tracked the
// legacy single MeetingRecorder lifecycle.

import { atom, appJotaiStore } from "../app-jotai";

export type RoomRecordingState = {
  /** True from the DO's `recording-state {recording:true}` until it broadcasts
   *  `recording:false` (owner stop / owner disconnect / ghost reaper). */
  recording: boolean;
  /** The lock owner's authenticated EMAIL — the AUTHORITATIVE identity the DO
   *  returns (its `owner.name` is always null, it has no DB). "this email is
   *  mine" ⇒ I hold the lock. Null while the room is not recording. */
  ownerEmail: string | null;
  /** The session id shared by EVERY file (mic / screen-audio / screen-video)
   *  recorded during this lock. Generated by the owner on acquire; carried in
   *  the DO broadcast so every participant's MicRecorder tags its upload with
   *  it. Null while not recording. */
  sessionId: string | null;
  /** Display name for the banner, RESOLVED CLIENT-SIDE from `ownerEmail` via the
   *  live collaborators/peer profiles (the DO never sends a name). Falls back to
   *  the email's local-part, then null. The RecordingIndicator reads this. */
  hostName: string | null;
  /** Legacy field kept ONLY so RecordingIndicator (which I don't own) still
   *  compiles — the DO has no socket id for the owner, so this is always null
   *  now. Name attribution flows through `hostName`/`ownerEmail` instead. */
  hostSocketId: string | null;
  /** When the recording began, ms since epoch (the owner's `startedAt`, echoed
   *  by the DO). Lets every peer paint an elapsed timer from one baseline. Null
   *  while not recording. */
  startedAt: number | null;
};

const IDLE_STATE: RoomRecordingState = {
  recording: false,
  ownerEmail: null,
  sessionId: null,
  hostName: null,
  hostSocketId: null,
  startedAt: null,
};

export const roomRecordingAtom = atom<RoomRecordingState>(IDLE_STATE);

export const setRoomRecording = (next: RoomRecordingState): void => {
  appJotaiStore.set(roomRecordingAtom, next);
};

export const resetRoomRecording = (): void => {
  appJotaiStore.set(roomRecordingAtom, IDLE_STATE);
};
