-- Division DEPUTY (Phase 2.1). The person one rank below the head ("cấp dưới
-- liền kề của người đứng đầu phòng ban", anh Luân 06-15) also gets project-
-- CREATE rights — so the head isn't the only one who can open projects. Nullable
-- (a one-person division has no deputy). Seeded from the directory (rank 2),
-- regenerated by `node worker/scripts/derive-divisions.mjs --deputies`.
ALTER TABLE division ADD COLUMN deputy_email TEXT;

-- AUTO-GENERATED by derive-divisions.mjs --deputies — deputy = rank 2.
UPDATE division SET deputy_email = 'dojin0721@mapgroup.co.kr' WHERE id = 'div-architectural-ai-r-and-d-center';
UPDATE division SET deputy_email = 'tkna@mapgroup.co.kr' WHERE id = 'div-architectural-design-div-1';
UPDATE division SET deputy_email = 'keirang@mapgroup.co.kr' WHERE id = 'div-architectural-design-div-2';
UPDATE division SET deputy_email = 'conpass@mapgroup.co.kr' WHERE id = 'div-business-administration-div';
UPDATE division SET deputy_email = 'his8770@mapgroup.co.kr' WHERE id = 'div-construction-management-div';
UPDATE division SET deputy_email = 'mij0207@mapgroup.co.kr' WHERE id = 'div-design-and-engineering-div-1';
UPDATE division SET deputy_email = 'goodman72@mapgroup.co.kr' WHERE id = 'div-design-and-engineering-div-2';
UPDATE division SET deputy_email = 'khpark@mapgroup.co.kr' WHERE id = 'div-design-and-engineering-div-3';
UPDATE division SET deputy_email = 'mf00850@mapgroup.co.kr' WHERE id = 'div-design-and-engineering-div-4';
UPDATE division SET deputy_email = 'nskim@mapgroup.co.kr' WHERE id = 'div-design-and-engineering-div-5';
UPDATE division SET deputy_email = 'ojm007@mapgroup.co.kr' WHERE id = 'div-design-and-engineering-div-6';
UPDATE division SET deputy_email = 'jk.ahn@mapgroup.co.kr' WHERE id = 'div-development-business-div';
UPDATE division SET deputy_email = 'hei1@mapgroup.co.kr' WHERE id = 'div-global-strategic-business-div';
UPDATE division SET deputy_email = 'ikk2537@mapgroup.co.kr' WHERE id = 'div-mapgroup';
UPDATE division SET deputy_email = 'kjkim345@mapgroup.co.kr' WHERE id = 'div-mechanical-design-div';
UPDATE division SET deputy_email = 'yskim@mapgroup.co.kr' WHERE id = 'div-plant-engineering-div';
UPDATE division SET deputy_email = 'cool0587@mapgroup.co.kr' WHERE id = 'div-q-tft';
UPDATE division SET deputy_email = 'hcchoi@mapgroup.co.kr' WHERE id = 'div-structural-design-div';
UPDATE division SET deputy_email = 'rua7880@mapgroup.co.kr' WHERE id = 'div-urban-architecture-div-1';
UPDATE division SET deputy_email = 'hmc750814@mapgroup.co.kr' WHERE id = 'div-urban-architecture-div-2';
UPDATE division SET deputy_email = 'kkpk987@mapgroup.co.kr' WHERE id = 'div-urban-design-div';
